Support more branch name formats
dagio/post-jira-comment-with-build-details-step pull request #7
Opened 2017-02-09 14:21 UTC by paour

Allow setting a Jira project so the branch name detection is more lenient.

Addresses #6 (except the part about passing in the issue ID.

2017-02-09 17:23 UTC, dagio requested changes
Thanks for the PR. Just few feedbacks

2017-02-09 17:23 UTC, dagio commented on step.yml
> +  - jira_project:
Is it the JIRA project key ? If so maybe we should make it explicit in the summary / description ?

2017-02-09 17:23 UTC, dagio commented on tests/IssueKeyResolverTest.php
> +            ['FOO-123', 'bugfix/FOO-123-Add-Something'],
The following case is missing : `['FOO-123', 'bug/FOO-123-Add-Something'],`

2017-02-09 17:23 UTC, dagio commented on tests/IssueKeyResolverTest.php
> +    public function testIssueKeyResolvedWithProject($expectedIssueKey, $branchName)
In that test you alter the branch name that is tested. It's not clear what you are trying to achieve. Maybe the following would make it more explicit :

```
$resolver = new IssueKeyResolver();
$branchNameWithoutProjectKey = str_replace('FOO-', '', $branchName);
$projectKey = 'FOO';
$actualIssueKey = $resolver->resolveKeyFromBranchName($branchNameWithoutProjectKey, $projectKey);
$this->assertEquals($expectedIssueKey, $actualIssueKey);
```

2017-02-09 17:34 UTC, paour commented
Done, thank you!

I didn't want to change composer files in a PR, but the repo seems to have some composer files (`vendor`, composer.lock`) that I imagine should be removed and added to `.gitignore` (but I know nothing about Composer…).

2017-02-10 11:50 UTC, dagio approved these changes

2017-02-10 11:51 UTC, dagio commented
I kept them in order to avoid to have to run `composer install` an slow down the build. We should actually just use a phar. That could be an improvement

2017-02-10 11:51 UTC, merged